import React from "react";
import { Button } from "react-native-paper";
import { LinearGradient } from "expo-linear-gradient";
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View, ScrollView, TouchableOpacity } from "react-native";
import { useNavigation } from "@react-navigation/native";
import Icon from "react-native-vector-icons/MaterialIcons";

export default function RefundPolicy() {
  const navigation = useNavigation();

  const backHandler = () => {
    navigation.goBack();
  };

  return (
    <LinearGradient
      colors={["#A01B3A", "#2C1738"]}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 0 }}
      style={styles.background}
    >
      <StatusBar style="auto" />
      <ScrollView
        style={styles.container}
        showsVerticalScrollIndicator={false} // hide the vertical scroll indicator
        contentContainerStyle={styles.contentContainer}
      >
        <TouchableOpacity style={styles.arrowBack} onPress={backHandler}>
          <Button
            icon={() => <Icon name="arrow-back" size={40} color="white" />} // Example icon with specific size and color
            onPress={backHandler}
            style={styles.button}
            labelStyle={styles.label}
          ></Button>
        </TouchableOpacity>

        <View>
  <Text style={styles.title}>Refund Policy</Text>
</View>

<View style={styles.content}>
  <Text style={styles.heading}>Refund Policy</Text>
  <Text style={styles.paragraph}>
    Thank you for shopping at Myitronline. If you are not entirely satisfied with your purchase, we're here to help.
  </Text>
  <Text style={styles.paragraph}>
    Returns: You have 30 calendar days to return an item from the date you received it. To be eligible for a return, your item must be unused and in the same condition that you received it. Your item must be in the original packaging. Your item needs to have the receipt or proof of purchase.
  </Text>
  <Text style={styles.paragraph}>
    Refunds: Once we receive your item, we will inspect it and notify you that we have received your returned item. We will immediately notify you on the status of your refund after inspecting the item. If your return is approved, we will initiate a refund to your credit card (or original method of payment). You will receive the credit within a certain amount of days, depending on your card issuer's policies.
  </Text>
  <Text style={styles.paragraph}>
    Shipping: You will be responsible for paying for your own shipping costs for returning your item. Shipping costs are non-refundable. If you receive a refund, the cost of return shipping will be deducted from your refund.
  </Text>
  <Text style={styles.paragraph}>
    Contact Us: If you have any questions on how to return your item to us, contact us at support@myitronline.com.
  </Text>
</View>

<View style={styles.contentMore}>
  <Text style={styles.heading}>Important Information</Text>
  <Text style={styles.paragraph}>
    a) This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
  </Text>
  <Text style={styles.paragraph}>
    b) This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of myitronline.com.
  </Text>
  <Text style={styles.paragraph}>
    c) The domain name www.myitronline.com ("Website"), is owned and operated by Myitronline Global Services Private limited. Company by shares, incorporated under the provisions of the Companies Act, 2013, and having its registered office: at 301, 3rd Floor Plot No. 51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.
  </Text>
</View>



      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: "center",
    width: "100%",
  },
  title: {
    fontSize: 20,
    color: "white",
    top:15,
    fontWeight: "bold",
  },
  arrowBack: {
    position: "absolute",
    top: 0,
    left: 0,
    padding: 10,
  },
  container: {
    marginTop: 50,
    width: "90%",
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: "center",
  },
  contentMore: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
  },
  content: {
    marginTop: 80,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
  },
  contentHeading: {
    fontSize: 20,
    backgroundColor: "#461738",
    padding: 10,
    borderRadius: 20,
    color: "white",
    fontWeight: "bold",
    marginBottom: 20,
  },
  heading: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    marginBottom: 10,
  },
  paragraph: {
    fontSize: 16,
    marginBottom: 10,
    textAlign: "justify",
    color: "black",
  },
});
