import React from "react";
import { Button } from "react-native-paper";
import { LinearGradient } from "expo-linear-gradient";
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View, ScrollView } from "react-native";
import { TouchableOpacity } from "react-native-gesture-handler";
import { useNavigation } from "@react-navigation/native";
import Icon from "react-native-vector-icons/MaterialIcons"; //
export default function TermsAndServices() {
  const navigation = useNavigation();

  const backHandler = () => {
    navigation.goBack();
  };

  return (
    <LinearGradient
      colors={["#A01B3A", "#2C1738"]}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 0 }}
      style={styles.background}
    >
      <StatusBar style="auto" />
      <ScrollView
        style={styles.container}
        showsVerticalScrollIndicator={false} // hide the vertical scroll indicator
        contentContainerStyle={styles.contentContainer}
      >
        <View style={styles.arrowBack}>
          <TouchableOpacity >
            <Button
              icon={() => <Icon name="arrow-back" size={40} color="white" />} // Example icon with specific size and color
              //   mode="contained"
              onPress={backHandler}
              style={styles.button}
              labelStyle={styles.label}
            ></Button>
          </TouchableOpacity>
        </View>
        <View >
          <Text style={styles.title}>Privacy And Services</Text>
        </View>

        <View style={styles.content}>
          <Text style={styles.heading}>Who we are</Text>
          <Text style={styles.paragraph}>
            Hello there and welcome to our Privacy Notice! This Notice applies
            to Myitronline, India’s largest and most trusted website that offers
            online preparation and filing of individual Income Tax Returns (ITR)
            or Legal Service. Established in 2011, Myitronline is based out of
            New Delhi. Since then, it has grown to build the largest customer
            base in this market segment. We work with business owners throughout
            their companies’ life cycles, helping them in legal and regulatory
            requirements and to overcome the obstacles blocking effective
            compliance.
          </Text>
          <Text style={styles.paragraph}>
            This Privacy Notice applies to personal data collected by
            Myitronline through the Myitronline.com website, myitronline.com
            website, and other websites which we operate and where we post a
            direct link to this Privacy Notice, including digital, paper, and
            in-person communications. This Privacy Notice does not cover
            handling of your personal data as an employee, intern, consultant,
            contractor, or applicant of Myitronline and does not cover any
            information collected by third-party sites or content or
            applications that may link to or be accessible from or on our
            websites. This Privacy Notice is provided in a layered format so you
            can click through to the specific areas set out below.
            Alternatively, you can download a pdf version of the policy here:
          </Text>
          <Text style={styles.contentHeading}>
            Please read this Privacy Notice carefully to understand how we
            collect and process personal data.
          </Text>
        </View>

        <View style={styles.contentMore}>
          <Text style={styles.heading}>Privacy of Customer Data</Text>
          <Text style={styles.paragraph}>
            a)This document is an electronic record in terms of Information
            Technology Act, 2000 and rules there under as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </Text>
          <Text style={styles.paragraph}>
            b)This document is published in accordance with the provisions of
            Rule 3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of
            myitronline.com
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            d)For the purpose of this Privacy Policy (“Policy”), wherever the
            context so requires. The term ‘You’ &‘User’ shall mean any legal
            person or entity accessing or using the services provided on this
            Website, who is competent to enter into binding contracts, as per
            the provisions of the Indian Contract Act, 1872; 
            {`\n`}
            {`\n`}
            The terms ‘We’,
            ‘Us’& ‘Our’ shall mean the Website and/or the Company, as the
            context so requires. 
            
            {`\n`}{`\n`}
            The terms ‘Party’ & ‘Parties’ shall
            respectively be used to refer to the User and the Company
            individually and collectively, as the context so requires.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
          <Text style={styles.paragraph}>
            c)The domain name www.myitronline.com ("Website"), is owned and
            operated by Myitronline Global Services Private limited. Company by
            shares, incorporated under the provisions of the Companies Act,
            2013, and having its registered office: at 301, 3rd Floor Plot No.
            51, Hasanpur, IP Extension, Patparganj, Delhi - 110092 where such
            expression shall, unless repugnant to the context thereof, be deemed
            to include its respective representatives, administrators,
            employees, directors, officers, agents and their successors and
            assigns.
          </Text>
        </View>
      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: "center",
    width: "100%",
  },
  title: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",
   
  },
  backButton: {
    width: 40, // Adjust the width and height as needed for the arrow button
    height: 40,
    color: "white",
    justifyContent: "center", // Center the icon vertically
    alignItems: "center", // Center the icon horizontally
  },
  arrowBack: {
    position: "absolute",
    top: 0,
    left: -20,
    paddingLeft: 10,
    paddingRight: 10,
  },
  container: {
    
    marginTop: 50,
    width: "90%",
  },
  contentContainer: {
    flexGrow: 1,
    alignItems: "center",

  },
  contentMore: {
    // backgroundColor: "#6C1A39",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingTop: 20,
    paddingLeft: 20,
    paddingRight: 20,

    marginBottom: 20,
    paddingHorizontal: 10,
  },
  content: {
    marginTop: 35,
    // backgroundColor: "#6C1A39",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingTop: 20,
    paddingLeft: 20,
    paddingRight: 20,

    marginBottom: 20,
    paddingHorizontal: 10, // Add horizontal padding to content
  },
  contentHeading: {
    fontSize: 20,
    backgroundColor: "#461738",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 20,
    color: "white", // Ensure heading is visible against the gradient background
    fontWeight: "bold",
    marginBottom: 20,
    color: "white", //
  },
  heading: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black", // Change text color to black
    marginBottom: 10,
    // color: "white", // Ensure heading is visible against the gradient background
  },
  paragraph: {
  fontSize: 16,
  marginBottom: 10,
  textAlign: "justify",
  color: "black", // Change text color to black
},
});
